/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DonationsStore } from "./DonationsStore";
export * as factories from "./factories";
export { DonationsStore__factory } from "./factories/DonationsStore__factory";
